// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpa7o0idVt2pNzGGHjMK5TTxmCY1y6zU',
    appId: '1:961031122781:web:143267b2e0facd154302b4',
    messagingSenderId: '961031122781',
    projectId: 'waste-management-7149d',
    authDomain: 'waste-management-7149d.firebaseapp.com',
    storageBucket: 'waste-management-7149d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9DUi8uFz6YMr_apZmFSlyOaAfMODX110',
    appId: '1:961031122781:android:91d15a54e31a944a4302b4',
    messagingSenderId: '961031122781',
    projectId: 'waste-management-7149d',
    storageBucket: 'waste-management-7149d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUogQQyg1nM-R_TbcftKsb-UU7_sOwi5A',
    appId: '1:961031122781:ios:6a5753a291de17094302b4',
    messagingSenderId: '961031122781',
    projectId: 'waste-management-7149d',
    storageBucket: 'waste-management-7149d.firebasestorage.app',
    iosBundleId: 'com.example.userManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUogQQyg1nM-R_TbcftKsb-UU7_sOwi5A',
    appId: '1:961031122781:ios:6a5753a291de17094302b4',
    messagingSenderId: '961031122781',
    projectId: 'waste-management-7149d',
    storageBucket: 'waste-management-7149d.firebasestorage.app',
    iosBundleId: 'com.example.userManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKpa7o0idVt2pNzGGHjMK5TTxmCY1y6zU',
    appId: '1:961031122781:web:d1159b0a818d0c9e4302b4',
    messagingSenderId: '961031122781',
    projectId: 'waste-management-7149d',
    authDomain: 'waste-management-7149d.firebaseapp.com',
    storageBucket: 'waste-management-7149d.firebasestorage.app',
  );
}
